HelpMyStreet/front-end

HelpMyStreetFE/HelpMyStreetFE/Views/Home/Index.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Home/_HeaderLogin.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_SiteNavigation.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/app.js, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/info-popup.js, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/site-nav.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/authentication/_header-login.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/header.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/input.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/main.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/mixins/forms/_inputs.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/site/_site-nav.scss
- Implemented site navigation for small and large screens
- Responsive site header
=> FE 33 Site navigation (mobile and desktop)

HelpMyStreetFE/HelpMyStreetFE/Views/Home/_HeaderLogin.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/app.js, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/site-header.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/colours.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/authentication/_header-login.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/header.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/main.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/mixins/typography/_copy.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/site/_site-nav.scss
Implements a first implementation of the site header authentication, including toggleable states on small screens.
Will need some work to match up with design so have just aimed to get it into a usable state to progress, then we can revisit to do the time-consuming refinements later.
There is a bug where if you open the login and then change resolution, the small screen state persists. Just needs a window resize event listener adding to resolve.
=> FE 40 Site header login - responsive

HelpMyStreetFE/HelpMyStreetFE/Views/Home/_HeaderLogin.cshtml
This adds the new header while retaining the ids for email and password inputs and the login button to resolve merge conflict issue.
=> FE 40 header

HelpMyStreetFE/HelpMyStreetFE/Views/Home/_HeaderLogin.cshtml
changed sign up link on mobile to point to registration/stepone
=> changed sign up link to be registration

HelpMyStreetFE/HelpMyStreetFE/Views/Yoti/_InstructionsDesktop.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Yoti/_InstructionsMobile.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/date-picker.js
Also fix some wording in the validation pages
=> Update default DOB

HelpMyStreetFE/HelpMyStreetFE/src/js/registration/step-three.js, HelpMyStreetFE/HelpMyStreetFE/src/js/registration/step-two.js, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/validator.js, HelpMyStreetFE/HelpMyStreetFE/wwwroot/yoti.js
note: To reduce Uneccesary calls to the postcode service, it only check if the post code is valid when all the rest of the validation has passed.
1.) Address line and City validation 
2.)
=> added call to check if postcod is valid

HelpMyStreetFE/HelpMyStreetFE/src/js/yoti.js
JS saves us all again (P.S. Mike is awesome)
=> Fix Mobile Journey

HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepTwo.cshtml
Suggested numbers had the wrong number of digits!
=> Fixed the suggested phone numbers

HelpMyStreetFE/HelpMyStreetFE/Controllers/ErrorsController.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Errors/404.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Errors/500.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Questions.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/date-picker.js
FE:212 Added logging in functionality on error pages
FE:211 - Corrected link for question 6 and added spacing for Q2. 
Also fixed validation bug that was defaulting the Under 18 message to Please enter a valid date of birth on submit of Step Two
=> FE-212, FE-211

HelpMyStreetFE/HelpMyStreetFE/Controllers/HomeController.cs, HelpMyStreetFE/HelpMyStreetFE/Startup.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Home/Login.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepThree.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_HeaderLogin.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_Layout.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_SiteHeaderOnlyLogo.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Yoti/_InstructionsDesktop.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Yoti/_InstructionsMobile.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/app.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/header.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/login.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/main.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/yoti.scss
FE:220 FOUC: (flash of unstyled content) - hide page, then when DOM has loaded, show page
FE-221: Step Five Verification Changes
FE-218: Seperate Login screen
No actual link to page yet, but can navigate to it using 
{url}/login
mobile:
=> FE-218: Login, FE-220: FOUC, FE-221: Step Five UI Tweaks

HelpMyStreetFE/HelpMyStreetFE/Controllers/AccountController.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/_Success.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepOne.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_Layout.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/registration/step-one.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/main.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/registration.scss
FE-195 - Coming soon content change
FE-168 Added spacing between links in footer
FE-45
No Checkboxs clicked
Privacy Only Clicked: 
Terms Only Clicked:
=> FE-195, FE-168, FE-45

HelpMyStreetFE/HelpMyStreetFE/Controllers/RequestHelpController.cs, HelpMyStreetFE/HelpMyStreetFE/HelpMyStreetFE.csproj, HelpMyStreetFE/HelpMyStreetFE/Models/Reponses/UpdateRequestResponse.cs, HelpMyStreetFE/HelpMyStreetFE/Models/RequestHelp/RequestHelpFormModel.cs, HelpMyStreetFE/HelpMyStreetFE/Repositories/IRequestHelpRepository.cs, HelpMyStreetFE/HelpMyStreetFE/Repositories/RequestHelpRepository.cs, HelpMyStreetFE/HelpMyStreetFE/Services/IRequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Services/RequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/RequestHelp.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/requesthelp.js, HelpMyStreetFE/HelpMyStreetFE/wwwroot/requesthelp.js
=> Removing Address selector, nuget packages updated, error handling

HelpMyStreetFE/HelpMyStreetFE/Controllers/AccountController.cs, HelpMyStreetFE/HelpMyStreetFE/Controllers/ErrorsController.cs, HelpMyStreetFE/HelpMyStreetFE/Controllers/HomeController.cs, HelpMyStreetFE/HelpMyStreetFE/Controllers/PagesController.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Home/ForgottonPasswordViewModel.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Home/ResetPasswordViewModel.cs, HelpMyStreetFE/HelpMyStreetFE/Models/HomeViewModel.cs, HelpMyStreetFE/HelpMyStreetFE/Models/LoginViewModel.cs, HelpMyStreetFE/HelpMyStreetFE/ViewComponents/HeaderLoginViewComponent.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/Login.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Errors/404.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Errors/500.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Home/ForgottonPassword.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Home/Index.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Home/ResetPassword.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/AboutUs.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Community.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/ContactUs.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/PrivacyPolicy.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Questions.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Resources.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Terms.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/Confirmation.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/Components/HeaderLogin/Default.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_SiteHeaderPublic.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/home/forgotton-password.js
I found a bug in Request Help that didn't let me log in and it was because we didn't include the BasePageViewModel  model, But this way was super bad and hacky so I've converted it to use ViewComponents instead so we essentially just do it once when we render the ViewComponent
=> Removed BasePageViewModel 

HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/RequestHelp.cshtml
=> labels fir inputs are now H5 tags

HelpMyStreetFE/HelpMyStreetFE/Views/Home/Index.cshtml
=> added d none to stats and checker

HelpMyStreetFE/HelpMyStreetFE/Views/Pages/PrivacyPolicy.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Terms.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/_cookie-grid.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/main.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/views/_content-page.scss
=> Fe 238 privacy policy update (includes new grid of cookies)

HelpMyStreetFE/HelpMyStreetFE/Views/Account/_MyStreets.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/Street.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/profile/_my-street.scss
Added  Explanatory text for Desktop and Mobile Views
Added Postcode to section headers in desktop
=> P1-100, P1-102, P1-110

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/Components/SiteHeader/Default.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/header.scss
Made spacing equal and aligned logo to middle
=> small ui tweaks

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/Components/SiteHeader/Default.cshtml
Just checked in comparison to what was there before and my last PR styling created some spacing that shouldn't of been there
=> removed spacing that i inadvertently added

HelpMyStreetFE/HelpMyStreetFE/Controllers/RegistrationController.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/Index.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepFour.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/_Stepper.cshtml
Reverted two commits
1.) Reverted "Remove Breadcrumb for step 5 and removed notification from profile"
2.) Reverted "Removed Step 5"
=> Revert 1.3

HelpMyStreetFE/HelpMyStreetFE/Controllers/YotiController.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/_ComingSoon.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepFour.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/verification.js, HelpMyStreetFE/HelpMyStreetFE/src/js/yoti.js
had to modify Yoti Controller Validate token to handle mobile responses. Making use of the mobile query string that yoti sends back to us. Also handling error responses from mobile.
(sorry for the bombardment of PRS)!!
=> Yoti Mobile Unhappy path.

HelpMyStreetFE/HelpMyStreetFE/Repositories/BaseHttpRepository.cs, HelpMyStreetFE/HelpMyStreetFE/Repositories/ValidationRepository.cs
Changed the verification call to not check for successful responses because we now need to check for a 401
=> Changed the verification call to not check for success response

HelpMyStreetFE/HelpMyStreetFE/Controllers/RequestHelpApiController.cs, HelpMyStreetFE/HelpMyStreetFE/Models/RequestHelp/RequestHelpViewModel.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Validation/ValidateRequestViewModelAttribute.cs, HelpMyStreetFE/HelpMyStreetFE/Services/RequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/DetailStage/_UserDetails.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/ReviewStage/_ReviewStage.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/detail-stage.js, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/requesthelp.js, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/review-stage.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/views/_request-help.scss
I added a class level validation attribute and placed all the rules in there. 
Also i sneaked in some bug fixes i spotted from my previous PR.
1.) Consent checkbox not being validated
2.) review personal details tiles not being the same size if address is too long on one.
3.) address line 1 and locality showing as "null" for requestor because they dont need to provide an address 
4.) edit address functionality wasn't working
=> Added server side validation

HelpMyStreetFE/HelpMyStreetFE.UnitTests/HelpMyStreetFE.UnitTests.csproj, HelpMyStreetFE/HelpMyStreetFE.UnitTests/Services/UserServiceTests.cs, HelpMyStreetFE/HelpMyStreetFE.sln, HelpMyStreetFE/HelpMyStreetFE/.gitignore, HelpMyStreetFE/HelpMyStreetFE/Services/UserService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/PrivacyPolicy.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/_cookie-grid.scss, azure-pipelines.yml
Add New Relic Browser cookies to cookie policy
Capitalise initials for display in banner and members area
Capitalise names during registration flow
Add some unit tests!
=> FE-302 FE-230

HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/requesthelp.js
added evt.stopimmediatePropegation - event was triggering multiple times
=> Duplicate Request Help Fix

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-34
=> P20-34 - converted to uk date

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/profile/_job.scss
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-51
Added line after communication needs and changed arrows to chevrons
=>  (REVIEW ORDER: 2) P20-51 : My Accepted Requests, "More Info" Drawer - Formatting

HelpMyStreetFE/HelpMyStreetFE/Controllers/AccountController.cs, HelpMyStreetFE/HelpMyStreetFE/Startup.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/_AcceptedRequests.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_AccountNavigation.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/profile.js, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/requests-popup-helper/open-requests.js, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/requests.js, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/verification.js
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-55
=> removed U from query string _ changed urls to conform with the rest

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_Popup.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/requests-popup-helper/accepted-requests.js, HelpMyStreetFE/HelpMyStreetFE/src/js/shared/popup.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/colours.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/_popup.scss
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-68
=> added cross and changed colour of button on release

HelpMyStreetFE/HelpMyStreetFE/Views/Account/_OpenRequests.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/profile/_job.scss
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-70
**Unverified** 
**Verified**
=> made accept and more info link grey for unverified users

HelpMyStreetFE/HelpMyStreetFE/src/js/profile/requests-popup-helper/open-requests.js
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-71
=> removed my accepted link

HelpMyStreetFE/HelpMyStreetFE/Views/Account/_AcceptedRequests.cshtml
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-67
=> make accepted requests default text italic

HelpMyStreetFE/HelpMyStreetFE/src/js/profile/requests.js
check for Job ID before we scoll
=> added check on job id div before we scroll

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml
https://helpmystreet.atlassian.net/jira/software/projects/P20/boards/10?selectedIssue=P20-77
=> checking user is verified to display info 

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml
https://helpmystreet.atlassian.net/browse/P20-83
=> swap requestor and recipient over

HelpMyStreetFE/HelpMyStreetFE/HelpMyStreetFE.csproj, HelpMyStreetFE/HelpMyStreetFE/Services/RequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/DetailStage/_UserDetails.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/detail-stage.js
Updated nuget package for ordering fixes
"Their email Address"  -> "Their email address"
disabled spaces
=> Review Order 1 - Updated Nuget Package + small fixes 

HelpMyStreetFE/HelpMyStreetFE/Controllers/RequestHelpApiController.cs, HelpMyStreetFE/HelpMyStreetFE/Services/IRequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Services/RequestService.cs
Refactored the trigger refresh code into private function and added it to log request
=> trigger cache refresh on new help for request 

HelpMyStreetFE/HelpMyStreetFE/src/sass/components/profile/_job.scss, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/tiles/_tiles.scss
=> logos shrinked

HelpMyStreetFE/HelpMyStreetFE/src/js/app.js, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/requesthelp.js
In IE the fetch api calls were throwing console errors because of a missing polyfill. Ollie stumbled across it by trying to accept a a request and the error was causing the UI to freeze
=> fixed IE issue where promises weren't defined

HelpMyStreetFE/HelpMyStreetFE/Controllers/RequestHelpController.cs, HelpMyStreetFE/HelpMyStreetFE/HelpMyStreetFE.csproj, HelpMyStreetFE/HelpMyStreetFE/Helpers/Extensions.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Account/RequestContactInformation.cs, HelpMyStreetFE/HelpMyStreetFE/Services/RequestService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepThree.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/DisplayTemplates/TaskTile.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/EditorTemplates/RequestHelpDetailStageViewModel.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/EditorTemplates/RequestHelpRequestStageViewModel.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/EditorTemplates/RequestHelpReviewStageViewModel.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/request-stage.js
Also added Time REquested back in, but just hide the the "today" and "within 24 hours option
**Requires Request Service to be deployed too**
=> Added questions to task management  + renamed face covering descriptions 

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/request-stage.js
=> removed S from face coverings friendly name

HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/detail-stage.js
and fix for phone number validation
=> allowing numbers in organisation name

HelpMyStreetFE/HelpMyStreetFE/Models/Validation/DetailStageValidationAttribute.cs, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/RequestHelp.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/sass/views/_request-help.scss
Missed code change from when we added requestor to Organisation Requestor type  
removed null checks since they happen in the functions. 
Also fixed back button styling on mobile (used to be one big back button and a small continue button)
=> server side validation fix for organisation

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml
Quite an urgent one, but Ollie Said he's happy for it go in with the next release provided that happens today
=> bug fix to show requestor in accepted requests

HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/detail-stage.js
Investigating : Request Help form not working on first submit. There was a scenario in the code that would potentially cause the spinner to never dissapear, so i added an error message and removed the spinner from the button in that scenario.
I also removed some console logs.
=> Added error in a scenario where the validating button could spin

HelpMyStreetFE/HelpMyStreetFE/Services/RequestHelpBuilder.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Shared/DisplayTemplates/JobSummary.cshtml
=> Diy requests - Removing Myself and Phone number fix 

HelpMyStreetFE/HelpMyStreetFE/Services/RequestHelpBuilder.cs, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/DisplayTemplates/RequestForTile.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/RequestHelp/_Questions.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/request-stage.js
removed pre selecting from back end and moved to Handle Activity Code function to allow pre selecting only if there is one requestor for tile. 
Scenario: FaceMask shouldnt pre select to Request On Behalf because you have the option to select more than one
=> added preselecting via jquery instead

HelpMyStreetFE/HelpMyStreetFE/src/js/requesthelp/detail-stage.js
Ollie Managed to replicate the issue and i was then able to replicate it locally.
**The Issue**
Jquery.Each function. 
Inside the JQuery each function we had a call to validate postcodes and within the $.each we had a check to see if the last postcode input had been checked, if it had then proceed to submit the form.
**However** sometimes the call back from the second postcode (which has an index 1) input would return sooner than first. This would cause the following code not to run. 
```
if (postcodeValid.length == (i + 1))  {
validForm = (validForm && !postcodeValid.includes(false));	
if (validForm) {	
$('form').unbind('submit') // continue the submit unbind preventDefault	
$('#btnNext').click();	
postcodeEl.next(".error").hide();	
} else {	
postcodeEl.next(".error").text("We could not …
```
=> fix for weird intermittent issue we saw on Friday

HelpMyStreetFE/HelpMyStreetFE/Controllers/RegistrationController.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Account/UserDetails.cs, HelpMyStreetFE/HelpMyStreetFE/Models/Registration/StepThreeFormModel.cs, HelpMyStreetFE/HelpMyStreetFE/Repositories/CommunityRepository.cs, HelpMyStreetFE/HelpMyStreetFE/Services/IUserService.cs, HelpMyStreetFE/HelpMyStreetFE/Services/UserService.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Account/_UserData.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepThree.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/registration/step-three.js
https://helpmystreet.atlassian.net/browse/FE-328
https://helpmystreet.atlassian.net/browse/FE-329
****
=> FE-328, FE-329

HelpMyStreetFE/HelpMyStreetFE/Views/Shared/_HelpExampleCards.cshtml, HelpMyStreetFE/HelpMyStreetFE/src/js/registration/step-three.js
=> Age uk wording

HelpMyStreetFE/HelpMyStreetFE/Views/Registration/StepThree.cshtml
=> FE-382 Convert 'people in need' to Jive equivalent

HelpMyStreetFE/HelpMyStreetFE/package-lock.json, HelpMyStreetFE/HelpMyStreetFE/package.json, HelpMyStreetFE/HelpMyStreetFE/src/js/profile/verification.js, HelpMyStreetFE/HelpMyStreetFE/src/sass/components/profile/_user-data.scss
=> FE-350 Align Yoti display with user agent rather than merely screen width

HelpMyStreetFE/HelpMyStreetFE/src/js/account/login.js
Wouldn't return success object if successful resulting in console error (but no functionality issues)
=> Fix minor login JS issue

HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Questions.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Pages/Terms.cshtml
=> Dull dull dull dull, Dull dull dull dull

HelpMyStreetFE/HelpMyStreetFE/Services/Requests/RequestHelpBuilder.cs, HelpMyStreetFE/HelpMyStreetFE/Views/Community/ApexPCNBankStaff.cshtml, HelpMyStreetFE/HelpMyStreetFE/Views/Community/Southwell.cshtml
Tweak to Southwell landing page
=> Tweaks to ApexBank

HelpMyStreetFE/HelpMyStreetFE/Models/Reponses/GetReportResponse.cs
=> remove stepSize
